# Generated by Django 2.2 on 2019-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d/'),
        ),
    ]
