# Generated by Django 2.2 on 2019-04-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20190414_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='wish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wish.Wish'),
        ),
    ]
